version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 987654321
      MYSQL_USER: ucredalunos
      MYSQL_PASSWORD: cred_P_alunos_W__db_D
      MYSQL_DATABASE: credalunos_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db-data:
