spring:
  batch:
    initialize-schema: always

  datasource:
    url: jdbc:mysql://localhost:3306/credalunos_db?createDatabaseIfNotExist=true
    username: root
    password: 987654321
  jpa:
    show-sql: true

file:
  chunk: lista_alunos.txt


  