spring:
  batch:
    initialize-schema: always

  datasource:
    url: jdbc:mysql://localhost:3306/credalunos_db?useUnicode=true&characterEnconding=UTF-8?useTimezone=true&serverTimezone=UTC
    username: ucredalunos
    password: cred_P_alunos_W__db_D
  jpa:
    show-sql: true

file:
  chunk: lista_alunos.txt
