server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/credalunos_db?createDatabaseIfNotExist=true
    username: root
    password: 987654321
  jpa:
    hibernate:
      naming:
        #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  flyway:
    baseline-on-migrate: true

    hibernate:
      ddl-auto: validate
