  
server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/credalunos_db?createDatabaseIfNotExist=true
    username: root
    password: 987654321
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
