  
server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch?useUnicode=true&characterEnconding=UTF-8?useTimezone=true&serverTimezone=UTC
    username: root
    password: 30914182
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  